#ifndef QMCCOMPILER_GLOBAL_H
#define QMCCOMPILER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QMCCOMPILER_LIBRARY)
#  define QMCCOMPILERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QMCCOMPILERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QMCCOMPILER_GLOBAL_H
